<a href="https://colab.research.google.com/github/CoderBabu143/CoderBabu143/blob/main/AD_SALE_PREDICTION_USING_LOGISTIC_REGRESSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# salary estimation using k-nearest neighbour

# importing *libraries*

In [3]:
import pandas as pd #useful for loading the dataset
import numpy as np #to perform array


# choose dataset from local ***directory***

In [4]:
from google.colab import files
uploaded=files.upload()


Saving AD SALE PREDICTION USING LR.csv to AD SALE PREDICTION USING LR.csv


LOAD DATASET

In [5]:
dataset=pd.read_csv("AD SALE PREDICTION USING LR.csv")
print(dataset)


    age  salary  status
0    18   16000       0
1    19   12220       1
2    19   17000       0
3    23   54321       1
4    24   12345       1
5    23   22000       0
6    22   12330       0
7    34   12330       1
8    24   17000       1
9    23   14400       1
10   26   17000       0
11   27   13500       1
12   28   12500       1
13   29   13350       0
14   32   13450       0
15   32   13660       1
16   31   13000       1
17   26   14000       1
18   22   13560       0
19   21   15550       1
20   20   17000       1
21   29   15750       0
22   27   16500       0
23   54   16660       1
24   55   16750       1
25   56   17000       1
26   51   18000       0
27   52   18500       1
28   50   18750       1


SUMMARIZE DATASET

In [6]:
print(dataset.shape)#no.of rows and columns
print(dataset.head(5))

(29, 3)
   age  salary  status
0   18   16000       0
1   19   12220       1
2   19   17000       0
3   23   54321       1
4   24   12345       1


SEGREGATE DATASET INTO X(INPUT/INDEPENDENT VARIABLE)&Y(OUTPUT/DEPENDENT VARIABLE)

In [7]:
X=dataset.iloc[:,:-1].values
X

array([[   18, 16000],
       [   19, 12220],
       [   19, 17000],
       [   23, 54321],
       [   24, 12345],
       [   23, 22000],
       [   22, 12330],
       [   34, 12330],
       [   24, 17000],
       [   23, 14400],
       [   26, 17000],
       [   27, 13500],
       [   28, 12500],
       [   29, 13350],
       [   32, 13450],
       [   32, 13660],
       [   31, 13000],
       [   26, 14000],
       [   22, 13560],
       [   21, 15550],
       [   20, 17000],
       [   29, 15750],
       [   27, 16500],
       [   54, 16660],
       [   55, 16750],
       [   56, 17000],
       [   51, 18000],
       [   52, 18500],
       [   50, 18750]])

In [8]:
Y=dataset.iloc[:,-1].values
Y

array([0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1])

SPLITTING DATASET INTO TRAIN&TEST

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

FEATURE SCALING

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
print(X_train)

[[-0.55954013  0.59218513]
 [ 0.43813048 -0.38702765]
 [-0.44868784  0.01954608]
 [ 0.32727819 -0.43856516]
 [-0.11613097 -0.03771783]
 [-0.22698326 -0.32403735]
 [-1.00294928 -0.52789685]
 [-0.22698326  0.01954608]
 [ 2.43347168  0.21996975]
 [-0.67039242 -0.51529879]
 [-0.44868784 -0.51358088]
 [-0.67039242 -0.37442959]
 [-0.78124471 -0.14651925]
 [-0.55954013 -0.27822623]
 [ 0.65983506 -0.51529879]
 [ 2.98773313 -0.00908587]
 [-0.55954013  4.29383849]
 [-1.11380157 -0.09498173]
 [ 0.10557361 -0.12361368]
 [ 0.43813048 -0.36297681]
 [-0.00527868 -0.49582907]]


TRAINING

In [11]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

PREDICTING WHETHER NEW CUSTOMER WITH AGE&SALARY WILL BUY OR NOT

In [19]:
age=int(input("enter new customer's age:"))
sal=int(input("enter new customer's salary:"))
newCust=[[age,sal]]
result=model.predict(sc.transform(newCust))
print(result)
if result==1:
  print("customer will buy")
else:
  print("customer won't buy")


enter new customer's age:95
enter new customer's salary:124000
[1]
customer will buy


PREDICTION FOR ALL TEST DATA

In [15]:
y_pred=model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]]


In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score
#cm=confusion_matrix(y_test,y_pred)
#print("confusion matrix:")
#print(cm)
print("accuracy of the model:{0}%".format(accuracy_score(y_test,y_pred)*100))

accuracy of the model:75.0%
